// <auto-generated />
using System;
using ArbitrageApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArbitrageApi.Migrations
{
    [DbContext(typeof(StatsDbContext))]
    [Migration("20260205212905_AddPnLFieldsToTransaction")]
    partial class AddPnLFieldsToTransaction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ArbitrageApi.Models.AggregatedMetric", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxSpread")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SumDepth")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("SumSpread")
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.ToTable("AggregatedMetrics");
                });

            modelBuilder.Entity("ArbitrageApi.Models.ArbitrageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DepthBuy")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("DepthSell")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pair")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Spread")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("SpreadPercent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ArbitrageEvents");
                });

            modelBuilder.Entity("ArbitrageApi.Models.HeatmapCell", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AvgSpread")
                        .HasColumnType("TEXT");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectionBias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hour")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxSpread")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VolatilityScore")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HeatmapCells");
                });

            modelBuilder.Entity("ArbitrageApi.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BuyCost")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("BuyOrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyOrderStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,8)");

                    b.Property<bool>("IsRecovered")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("RealizedProfit")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("RecoveryOrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SellOrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SellOrderStatus")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SellProceeds")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Strategy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalFees")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
