// <auto-generated />
using System;
using ArbitrageApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArbitrageApi.Migrations
{
    [DbContext(typeof(StatsDbContext))]
    [Migration("20260127114914_InitialStatsCreate")]
    partial class InitialStatsCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ArbitrageApi.Models.ArbitrageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DepthBuy")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("DepthSell")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pair")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Spread")
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ArbitrageEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
